### ISSUE TITLE
Alternate config schema

### ISSUE THREAD

**Issue by saitho** [getstackhead/stackhead#131]
While YAML files are easy to process, an alternate config schema may be easier to maintain.

## Domain declaration

Usecase:
I want to service the application running inside the service "myservice" on port 8080 on the domain "mydomain.com" on port 80. It should require Basic Authentication with username "user" and password "pass".
The application has a WebSocket endpoint on path /socket.

### Old

Taken from [documentation](https://docs.stackhead.io/introduction/project-definition)

```yaml
domains:
  - domain: kimai.saitho.me
    expose:
      - internal_port: 8080
        external_port: 80
        service: myservice
        proxy_websocket_locations: ["/socket"]
    security:
        authentication:
            - type: basic # basic authentication: users will have to authenticate with username ("user") and password ("pass")
              username: user
              password: pass
```

### New
```
domain mydomain.com {
    :80 {
        service = myservice
        port = 8080
        proxy_websocket_location {
            path = /socket
        }
    }
    security {
        authentication {
            type = basic
            username = user
            password = pass
        }
    }
}
```

### Old

Taken from [documentation](https://docs.stackhead.io/introduction/project-definition)

```yaml
container:
  services:
    - name: app # service name
      image: nginxdemos/hello:latest # Docker image name
      volumes:
        - type: global # mount the "config" folder inside container at "/var/config". As both services use "global" they will mount the same source and share data.
          src: config
          dest: /var/config
        - type: local # mount the "data" folder inside container at "/var/data". This folder is not shared with other services ("local").
          src: data
          dest: /var/data
        - type: custom # mount the "/docker/data/test" folder inside container at "/var/test".
          src: /docker/data/test
          dest: /var/test
      hooks:
        execute_after_setup: ./setup.sh # this file is executed inside container after the container is created
        execute_before_destroy: ./destroy.sh # this file is executed inside container before the container is destroyed
    - name: db # service name
      image: mariadb:10.5 # Docker image name
      environment: # environment variables for Docker container
        MYSQL_ROOT_PASSWORD: example
      volumes_from: app:ro # mount all volumes from app service as readonly
```

### New

???
