### ISSUE TITLE
Publish as Ansible collection instead of individual Package Manager packages

### ISSUE THREAD

**Issue by saitho** [getstackhead/stackhead#20]
In requirements.yaml file one can specify package, repository and version like so:

```yaml
- src: https://github.com/bennojoy/nginx
  version: master
  name: nginx_role
```

The issue with that is that StackHead uses Git submodules which are not intialized then, resulting in errors.
Instead we should look into Collections: https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html
