### ISSUE TITLE
Wait for Terraform lockfile

### ISSUE THREAD

**Issue by saitho** [getstackhead/stackhead#98]
When Terraform runs, it creates a lockfile `.terraform.tfstate.lock.info` where it runs.
When wanting to run Terraform apply we should check if that file exists and wait until it is removed (i.e. the previous process finished). There should be a maximum timeout after which the execution will abort and fail.

**Comment by saitho** [comment]
Maybe we can use "retries" and "delay": https://stackoverflow.com/a/55190070/5457046

**Comment by saitho** [comment]
This should work?

```yaml
wait_for:
    path: /stackhead/terraform/projects/.terraform.tfstate.lock.info
    state: absent
```
